default/objects/Account/fields/Guild__c.field-meta.xml
<CustomField>
    <fullName>Guild__c</fullName>
    <label>Guild</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Guild</valueSetName>
    </valueSet>
</CustomField>

default/objects/Account/fields/TaxNumber__c.field-meta.xml
<CustomField>
    <fullName>TaxNumber__c</fullName>
    <externalId>true</externalId>
    <label>Tax Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Case/fields/ClaimDate__c.field-meta.xml
<CustomField>
    <fullName>ClaimDate__c</fullName>
    <label>Claim Date</label>
    <type>Date</type>
</CustomField>

default/objects/Case/fields/ClaimsHandlerEmail__c.field-meta.xml
<CustomField>
    <fullName>ClaimsHandlerEmail__c</fullName>
    <label>Claims Handler Email</label>
    <type>Email</type>
</CustomField>

default/objects/Case/fields/ClaimsHandlerName__c.field-meta.xml
<CustomField>
    <fullName>ClaimsHandlerName__c</fullName>
    <label>Claims Handler Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

default/objects/Case/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <label>Coverage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CE</fullName>
                <label>Continente</label>
            </value>
            <value>
                <fullName>CO</fullName>
                <label>Contenido</label>
            </value>
            <value>
                <fullName>ECE</fullName>
                <label>Esteticos continente</label>
            </value>
            <value>
                <fullName>ECO</fullName>
                <label>Esteticos contenido</label>
            </value>
            <value>
                <fullName>RC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Case/fields/GCOrderNumber__c.field-meta.xml
<CustomField>
    <fullName>GCOrderNumber__c</fullName>
    <label>GC Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Case/fields/GrandAccount__c.field-meta.xml
<CustomField>
    <fullName>GrandAccount__c</fullName>
    <label>Grand Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SLA</fullName>
            </value>
            <value>
                <fullName>PLYO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Case/fields/LastIntegrationDateTime__c.field-meta.xml
<CustomField>
    <fullName>LastIntegrationDateTime__c</fullName>
    <label>Last Integration Date/Time</label>
    <type>DateTime</type>
</CustomField>

default/objects/Case/fields/LastIntegrationDescription__c.field-meta.xml
<CustomField>
    <fullName>LastIntegrationDescription__c</fullName>
    <label>Last Integration Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Case/fields/ParticipationDate__c.field-meta.xml
<CustomField>
    <fullName>ParticipationDate__c</fullName>
    <label>Participation Date</label>
    <type>Date</type>
</CustomField>

default/objects/Case/fields/PolicyNumber__c.field-meta.xml
<CustomField>
    <fullName>PolicyNumber__c</fullName>
    <label>Policy Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

default/objects/Case/fields/RelationshiptotheInsured__c.field-meta.xml
<CustomField>
    <fullName>RelationshiptotheInsured__c</fullName>
    <label>Relationship to the Insured</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CY</fullName>
                <label>Cónyuge</label>
            </value>
            <value>
                <fullName>HI</fullName>
                <label>Hijo</label>
            </value>
            <value>
                <fullName>FA</fullName>
                <label>Familiar</label>
            </value>
            <value>
                <fullName>VE</fullName>
                <label>Vecino</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Case/fields/TaxNumber__c.field-meta.xml
<CustomField>
    <fullName>TaxNumber__c</fullName>
    <formula>Contact.IDNumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tax Number</label>
    <type>Text</type>
</CustomField>

default/objects/Contact/fields/BuildingCapital__c.field-meta.xml
<CustomField>
    <fullName>BuildingCapital__c</fullName>
    <label>Building Capital</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

default/objects/Contact/fields/FillingCapital__c.field-meta.xml
<CustomField>
    <fullName>FillingCapital__c</fullName>
    <label>Filling Capital</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

default/objects/Contact/fields/IDNumber__c.field-meta.xml
<CustomField>
    <fullName>IDNumber__c</fullName>
    <label>Identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Contact/fields/LastIntegrationDateTime__c.field-meta.xml
<CustomField>
    <fullName>LastIntegrationDateTime__c</fullName>
    <label>Last Integration Date/Time</label>
    <type>DateTime</type>
</CustomField>

default/objects/Contact/fields/LastIntegrationDescription__c.field-meta.xml
<CustomField>
    <fullName>LastIntegrationDescription__c</fullName>
    <label>Last Integration Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Contact/fields/LiabilityCapital__c.field-meta.xml
<CustomField>
    <fullName>LiabilityCapital__c</fullName>
    <label>Liability Capital</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

default/objects/Contact/fields/LineOfBusiness__c.field-meta.xml
<CustomField>
    <fullName>LineOfBusiness__c</fullName>
    <description>Line of business of the policy.</description>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0007</fullName>
                <label>SEGURO DE INCENDIOS</label>
            </value>
            <value>
                <fullName>0008</fullName>
                <label>ROBO Y EXPOLIACIÓN</label>
            </value>
            <value>
                <fullName>0009</fullName>
                <label>ROTURA DE LUNAS Y CRISTALES</label>
            </value>
            <value>
                <fullName>0010</fullName>
                <label>ACCIDENTES INDIVIDUALES</label>
            </value>
            <value>
                <fullName>0011</fullName>
                <label>PERDIDA DE BENEFICIOS</label>
            </value>
            <value>
                <fullName>0012</fullName>
                <label>RESPONSABILIDAD CIVIL</label>
            </value>
            <value>
                <fullName>0013</fullName>
                <label>L.A HOGAR</label>
            </value>
            <value>
                <fullName>0014</fullName>
                <label>LAGUN ARO COMERCIO</label>
            </value>
            <value>
                <fullName>0015</fullName>
                <label>LAGUN ARO COMUNIDAD</label>
            </value>
            <value>
                <fullName>0016</fullName>
                <label>COLECTIVO DE ACCIDENTES</label>
            </value>
            <value>
                <fullName>0017</fullName>
                <label>COMBINADO INDUSTRIAL</label>
            </value>
            <value>
                <fullName>0018</fullName>
                <label>T. R. CONSTRUCCIÓN</label>
            </value>
            <value>
                <fullName>0019</fullName>
                <label>EQUIPOS ELECTRÓNICOS</label>
            </value>
            <value>
                <fullName>0020</fullName>
                <label>TRANSPORTE DE MERCANCÍAS</label>
            </value>
            <value>
                <fullName>0021</fullName>
                <label>ROTURA DE MAQUINARIA</label>
            </value>
            <value>
                <fullName>0022</fullName>
                <label>TODO RIESGO MONTAJE</label>
            </value>
            <value>
                <fullName>0023</fullName>
                <label>CANCELACION ESPECTÁCULO</label>
            </value>
            <value>
                <fullName>0024</fullName>
                <label>LAGUN ARO COMBINADA AGRÍCOLA</label>
            </value>
            <value>
                <fullName>0025</fullName>
                <label>GARANTIA DECENAL</label>
            </value>
            <value>
                <fullName>0026</fullName>
                <label>ACCIDENTES GANADO OVINO</label>
            </value>
            <value>
                <fullName>0027</fullName>
                <label>PROTECCION DE PAGOS</label>
            </value>
            <value>
                <fullName>0028</fullName>
                <label>TODO  RIESGO DE  DAÑOS MATERIALES</label>
            </value>
            <value>
                <fullName>0029</fullName>
                <label>RESPONSABILIDAD CIVIL CAZADOR</label>
            </value>
            <value>
                <fullName>0030</fullName>
                <label>EMBARCACIONES DE RECREO</label>
            </value>
            <value>
                <fullName>0031</fullName>
                <label>AON @ LAGUN ARO PYME</label>
            </value>
            <value>
                <fullName>0032</fullName>
                <label>LAGUN ARO NEGOCIO</label>
            </value>
            <value>
                <fullName>0033</fullName>
                <label>0033 - LAGUN ARO NEGOCIO</label>
            </value>
            <value>
                <fullName>0034</fullName>
                <label>PATINETES ELECTRICOS Y BICICLETAS</label>
            </value>
            <value>
                <fullName>0035</fullName>
                <label>Hogar - Extracontractual</label>
            </value>
            <value>
                <fullName>0036</fullName>
                <label>Hogar - Básico</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Contact/fields/PolicyNumber__c.field-meta.xml
<CustomField>
    <fullName>PolicyNumber__c</fullName>
    <externalId>true</externalId>
    <label>Policy Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Contact/fields/PolicyStartDate__c.field-meta.xml
<CustomField>
    <fullName>PolicyStartDate__c</fullName>
    <label>Policy Start Date</label>
    <type>Date</type>
</CustomField>

default/objects/Order/fields/CaseNumber__c.field-meta.xml
<CustomField>
    <fullName>CaseNumber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Order/fields/ClaimDate__c.field-meta.xml
<CustomField>
    <fullName>ClaimDate__c</fullName>
    <label>Claim Date</label>
    <type>Date</type>
</CustomField>

default/objects/Order/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <label>Coverage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Covered</fullName>
            </value>
            <value>
                <fullName>Not covered</fullName>
            </value>
            <value>
                <fullName>Rejection</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Order/fields/GCOrderNumber__c.field-meta.xml
<CustomField>
    <fullName>GCOrderNumber__c</fullName>
    <label>GC Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Order/fields/Guild__c.field-meta.xml
<CustomField>
    <fullName>Guild__c</fullName>
    <label>Guild</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Guild</valueSetName>
    </valueSet>
</CustomField>

default/objects/Order/fields/iFrame__c.field-meta.xml
<CustomField>
    <fullName>iFrame__c</fullName>
    <label>iFrame</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/Order/fields/LastIntegrationDateTime__c.field-meta.xml
<CustomField>
    <fullName>LastIntegrationDateTime__c</fullName>
    <label>Last Integration Date/Time</label>
    <type>DateTime</type>
</CustomField>

default/objects/Order/fields/LastIntegrationDescription__c.field-meta.xml
<CustomField>
    <fullName>LastIntegrationDescription__c</fullName>
    <label>Last Integration Description</label>
    <type>TextArea</type>
</CustomField>

default/objects/Stakeholders__c/Stakeholders__c.object-meta.xml
<CustomObject>
    <label>Stakeholder</label>
    <nameField>
        <label>Stakeholders Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stakeholders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Stakeholders__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Third_Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Stakeholders__c/fields/LastIntegrationDateTime__c.field-meta.xml
<CustomField>
    <fullName>LastIntegrationDateTime__c</fullName>
    <label>Last Integration Date/Time</label>
    <type>DateTime</type>
</CustomField>

default/objects/Stakeholders__c/fields/LastIntegrationDescription__c.field-meta.xml
<CustomField>
    <fullName>LastIntegrationDescription__c</fullName>
    <label>Last Integration Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Stakeholders__c/fields/OnthePortal__c.field-meta.xml
<CustomField>
    <fullName>OnthePortal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>On the Portal</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Stakeholders__c/fields/StakeholderTaxID__c.field-meta.xml
<CustomField>
    <fullName>StakeholderTaxID__c</fullName>
    <label>Stakeholder Tax ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

default/objects/Stakeholders__c/fields/StakeholderType__c.field-meta.xml
<CustomField>
    <fullName>StakeholderType__c</fullName>
    <label>Stakeholder Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C</fullName>
                <label>Causante</label>
            </value>
            <value>
                <fullName>P</fullName>
                <label>Prejudicado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/classes/CreateNewServiceControllerTest.cls
/**
 * @description       : Test class for CreateNewServiceController MKIS service creation and update operations
 * @author            : Daniel Flores
 * @group             : 
 * @last modified on  : 07-05-2026
 * @last modified by  : Daniel Flores
**/
@isTest
private class CreateNewServiceControllerTest {
    
    private class CreateNewServiceMock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');

            if (req.getEndpoint().contains('/api/service')) {
                String jsonBody = JSON.serializePretty(new Map<String, Object>{
                    'info' => new Map<String, Object>{
                        'headers' => new Map<String, Object>(),
                        'original' => new Map<String, Object>{
                            'iframe_elba' => 'https://dev.tooltoelba.es/elbaDirectAuthByIframe/685908bff2c0f',
                            'message' => 'Success from mock'
                        },
                        'exception' => null
                    }
                });
                res.setBody('{"message":"Servicio actualizado con éxito","data":{"iframe_elba":"https://dev.tooltoelba.es/elbaDirectAuthByIframe/687e68e06c258","service":{"id":2,"service_insurance_id":"4","gc_charge_number":"123123321","sinister_date":"2025-07-22","elba_insured_name":"Daniel Flores"},"intervener":null,"message":"Servicio actualizado con éxito"}}');
                res.setStatusCode(200);
            } else if (req.getEndpoint().contains('/api/login')) {
                res.setBody('{"token":"fake-token"}');
                res.setStatusCode(200);
            } else {
                res.setBody('{"error":"Unknown endpoint"}');
                res.setStatusCode(404);
            }

            return res;
        }
        
    }

    private class CreateNewServiceMock2 implements HttpCalloutMock {
        

        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');

            if (req.getEndpoint().contains('/api/service')) {
                
                res.setBody('{"message":"Campos inv\u00e1lidos","data":["elba capital efificio debe ser num\u00e9rico.","elba capital responsabilidade civil debe ser num\u00e9rico."]}');
                res.setStatusCode(400);
            } else if (req.getEndpoint().contains('/api/login')) {
                res.setBody('{"token":"fake-token"}');
                res.setStatusCode(200);
            } else {
                res.setBody('{"error":"Unknown endpoint"}');
                res.setStatusCode(404);
            }

            return res;
        }
        
    }

    /**
     * @description Creates test data including Account, Contact, Case, Order, and Stakeholder records for service tests
     */
    @testSetup
    static void setupTestData() {
        Account acc = new Account(
            Name = 'Test Provider',
            TaxNumber__c = '123456789',
            Phone = '211234567',
            Email__c = 'provider@example.com'
        );
        insert acc;

        Contact contact = new Contact(
            LastName = 'Test Contact',
            PolicyNumber__c = '123456',
            MailingStreet = 'Rua Exemplo 123',
            MailingPostalCode = '1000-001',
            Phone = '211234567',
            MobilePhone = '911234567',
            Email = 'contact@example.com',
            IDNumber__c = '987654321',
            BuildingCapital__c = 100000,
            FillingCapital__c = 20000,
            LiabilityCapital__c = 50000
        );
        insert contact;

        Case testCase = new Case(
            Subject = 'Test Case',
            GrandAccount__c = 'SLA',
            GCOrderNumber__c = 'GC789',
            ClaimDate__c = Date.today(),
            Coverage__c = '1',
            Description = 'Danos causados por inundação'
        );
        insert testCase;

        Order ord = new Order(
            AccountId = acc.Id,
            BillToContactId = contact.Id,
            CaseNumber__c = testCase.Id,
            Type = 'Serviço Técnico',
            EffectiveDate = Date.today(),
            Status = 'Active'
        );
        insert ord;

        Order ord2 = new Order(
            AccountId = acc.Id,
            BillToContactId = contact.Id,
            CaseNumber__c = testCase.Id,
            Type = 'Serviço Standard',
            EffectiveDate = Date.today(),
            Status = 'Active'
        );
        insert ord2;

        Stakeholders__c stakeholder = new Stakeholders__c(
            OnThePortal__c = false,
            Case__c = testCase.Id,
            Name = 'Test Contact',
            StakeholderType__c = 'Causante',
            StakeholderTaxID__c = '123456789',
            Phone__c = '911234567',
            Address__Street__s = 'Rua Stakeholder 1',
            Address__City__s = 'Lisboa',
            Address__PostalCode__s = '1000-001'
        );
        insert stakeholder;
    }

    /**
     * @description Tests the redirect method that invokes service creation for an Order
     */
    @isTest
    static void testRedirectMethod() {
        Test.setMock(HttpCalloutMock.class, new CreateNewServiceMock());

        Order ord = [SELECT Id FROM Order LIMIT 1];

        Test.startTest();
        CreateNewServiceController.redirectMethod(new List<String>{ ord.Id });
        Test.stopTest();

        // Verifica se foi criado um valor esperado no Order
        Order updatedOrder = [SELECT LastIntegrationDateTime__c, LastIntegrationDescription__c, iFrame__c FROM Order WHERE Id = :ord.Id];
       
    }

    /**
     * @description Tests successful creation of a new MKIS service from an Order
     */
    @isTest
    static void testCreateNewServiceMethod_Success() {
        Test.setMock(HttpCalloutMock.class, new CreateNewServiceMock());

        Order ord = [SELECT Id FROM Order LIMIT 1];

        Test.startTest();
        CreateNewServiceController.createNewServiceMethod(new List<String>{ ord.Id });
        Test.stopTest();

        Order updatedOrder = [SELECT LastIntegrationDateTime__c, LastIntegrationDescription__c FROM Order WHERE Id = :ord.Id];
        
    }

    /**
     * @description Tests that validateMandatoryFields returns the expected missing fields when data is incomplete
     */
    @isTest
    static void testValidateMandatoryFields_ReturnsMissingFields() {
        Order ord = [SELECT Id FROM Order LIMIT 1];

        Test.startTest();
        List<String> missingFields = CreateNewServiceController.validateMandatoryFields(ord.Id);
        Test.stopTest();

        // Sanity checks: some fields are intentionally missing in test setup.
        System.assert(missingFields.contains('operatorName'));
        System.assert(missingFields.contains('policyEffectiveDate'));
        System.assert(missingFields.contains('assignedJob'));
        System.assert(missingFields.contains('city'));

        // Stakeholders exist and were populated to be valid.
        System.assert(!missingFields.contains('stakeholderName'));
        System.assert(!missingFields.contains('stakeholderType'));
        System.assert(!missingFields.contains('stakeholderTaxNumber'));
        System.assert(!missingFields.contains('stakeholderPhoneNumber'));
        System.assert(!missingFields.contains('stakeholderAddress'));
    }

    /**
     * @description Tests that validateMandatoryFields returns an empty list when all mandatory fields are populated
     */
    @isTest
    static void testValidateMandatoryFields_ReturnsEmptyWhenAllMappedFieldsExist() {
        Contact contact = [
            SELECT Id, MailingCity, MailingState, PolicyStartDate__c, /* LineOfBusiness__c, */
                   Phone, MobilePhone, Email, MailingStreet, MailingPostalCode
            FROM Contact
            LIMIT 1
        ];
        contact.MailingCity = 'Lisboa';
        contact.MailingState = 'Lisboa';
        contact.PolicyStartDate__c = Date.today();
       /*  contact.LineOfBusiness__c = '01-HOGAR'; */
        update contact;

        Case caseTemp = [
            SELECT Id, ClaimsHandlerName__c, ClaimsHandlerEmail__c,
                   RelationshiptotheInsured__c, ParticipationDate__c
            FROM Case
            LIMIT 1
        ];
        caseTemp.ClaimsHandlerName__c = 'Handler Name';
        caseTemp.ClaimsHandlerEmail__c = 'handler@example.com';
        caseTemp.RelationshiptotheInsured__c = 'CY';
        caseTemp.ParticipationDate__c = Date.today();
        update caseTemp;

        Order ord = [SELECT Id, Guild__c FROM Order LIMIT 1];
        ord.Guild__c = 'Electricidad';
        update ord;

        Test.startTest();
        List<String> missingFields = CreateNewServiceController.validateMandatoryFields(ord.Id);
        Test.stopTest();

        System.assertEquals(0, missingFields.size());
    }

    /**
     * @description Tests unsuccessful service update when the API returns an error response
     */
    @isTest
    static void testUpdateServiceMethod_UnSuccess() {
        Test.setMock(HttpCalloutMock.class, new CreateNewServiceMock2());

        Case caseTemp = [SELECT Id FROM Case LIMIT 1];

        Test.startTest();
        CreateNewServiceController.createNewServiceMethod(new List<String>{ caseTemp.Id });
        Test.stopTest();

        Order updatedOrder = [SELECT LastIntegrationDateTime__c, LastIntegrationDescription__c FROM Order WHERE CaseNumber__c = :caseTemp.Id LIMIT 1];
        
    }
    /**
     * @description Tests unsuccessful service creation when the API returns an error response
     */
    @isTest
    static void testCreateNewServiceMethod_UnSuccess() {
        Test.setMock(HttpCalloutMock.class, new CreateNewServiceMock2());

        Order ord = [SELECT Id FROM Order LIMIT 1];

        Test.startTest();
        CreateNewServiceController.createNewServiceMethod(new List<String>{ ord.Id });
        Test.stopTest();

        Order updatedOrder = [SELECT LastIntegrationDateTime__c, LastIntegrationDescription__c FROM Order WHERE Id = :ord.Id];
        
    }

    /**
     * @description Tests a second unsuccessful service update scenario when the API returns an error response
     */
    @isTest
    static void testUpdateServiceMethod_UnSuccess2() {
        Test.setMock(HttpCalloutMock.class, new CreateNewServiceMock2());

        Case caseTemp = [SELECT Id FROM Case LIMIT 1];

        Test.startTest();
        CreateNewServiceController.createNewServiceMethod(new List<String>{ caseTemp.Id });
        Test.stopTest();

        Order updatedOrder = [SELECT LastIntegrationDateTime__c, LastIntegrationDescription__c FROM Order WHERE CaseNumber__c = :caseTemp.Id LIMIT 1];
        
    }
}