default/objects/Account/fields/Guild__c.field-meta.xml
<CustomField>
    <fullName>Guild__c</fullName>
    <label>Guild</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Guild</valueSetName>
    </valueSet>
</CustomField>

default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <label>Supplier</label>
</RecordType>

default/objects/Order/fields/CaseNumber__c.field-meta.xml
<CustomField>
    <fullName>CaseNumber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Order/fields/ChargeIdentifier__c.field-meta.xml
<CustomField>
    <fullName>ChargeIdentifier__c</fullName>
    <externalId>true</externalId>
    <label>Charge Identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Order/fields/Guild__c.field-meta.xml
<CustomField>
    <fullName>Guild__c</fullName>
    <label>Guild</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Guild</valueSetName>
    </valueSet>
</CustomField>

default/objects/Order/fields/Observaciones__c.field-meta.xml
<CustomField>
    <fullName>Observaciones__c</fullName>
    <label>Observations</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Order/fields/OPFVTSIndicatorsPresent__c.field-meta.xml
<CustomField>
    <fullName>OPFVTSIndicatorsPresent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OPF/VTS Indicators Present</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Order/fields/ProviderReference__c.field-meta.xml
<CustomField>
    <fullName>ProviderReference__c</fullName>
    <label>Provider Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Order/fields/ProviderType__c.field-meta.xml
<CustomField>
    <fullName>ProviderType__c</fullName>
    <label>Provider Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MU</fullName>
                <label>Multi-trade</label>
            </value>
            <value>
                <fullName>MA</fullName>
                <label>Handyman</label>
            </value>
            <value>
                <fullName>DE</fullName>
                <label>Drain Unblocking</label>
            </value>
            <value>
                <fullName>CE</fullName>
                <label>Locksmith</label>
            </value>
            <value>
                <fullName>CR</fullName>
                <label>Glazing</label>
            </value>
            <value>
                <fullName>ELBA</fullName>
                <label>Electrical</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>Carpentry</label>
            </value>
            <value>
                <fullName>PA</fullName>
                <label>Flooring (Parquet)</label>
            </value>
            <value>
                <fullName>LS</fullName>
                <label>Sanitary Ware</label>
            </value>
            <value>
                <fullName>ST</fullName>
                <label>Technical Service</label>
            </value>
            <value>
                <fullName>TC</fullName>
                <label>Boiler Technician</label>
            </value>
            <value>
                <fullName>OT</fullName>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Order/fields/RelatedOrder__c.field-meta.xml
<CustomField>
    <fullName>RelatedOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Order/fields/Urgent__c.field-meta.xml
<CustomField>
    <fullName>Urgent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Urgent</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Order/fields/UrlLinkStatus__c.field-meta.xml
<CustomField>
    <fullName>UrlLinkStatus__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Urlink Status</label>
    <type>Checkbox</type>
</CustomField>

default/classes/MKISElbaOrderTriggerLogicTest.cls
/**
 * @description       : Test class for MKISElbaOrderTriggerLogic - validates MKIS-specific Order trigger logic
 *                      including Create/Update Service and Create Contact dispatching
 * @author            : Daniel Flores
 * @last modified on  : 30-04-2026
 * @last modified by  : Daniel Flores
**/
@IsTest
private class MKISElbaOrderTriggerLogicTest {

    /**
     * @description Mock HTTP callout class for simulating MKIS ELBA API responses
     */
    private class MKISElbaMock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(200);
            res.setBody('{"message":"Success"}');
            return res;
        }
    }

    /**
     * @description Sets up test data including Account with Supplier RecordType, Contract, and Order
     */
    @TestSetup
    static void setupTestData() {
        Account testAccount = new Account(Name = 'Test Supplier MKIS');
        insert testAccount;

        Contact testContact = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            AccountId = testAccount.Id
        );
        insert testContact;

        Contract testContract = new Contract(
            AccountId = testAccount.Id,
            Status = 'Draft',
            StartDate = Date.today(),
            ContractTerm = 12
        );
        insert testContract;

        Order testOrder = new Order(
            AccountId = testAccount.Id,
            ContractId = testContract.Id,
            BillToContactId = testContact.Id,
            EffectiveDate = Date.today(),
            Status = 'Draft'
        );
        insert testOrder;
    }

    /**
     * @description Tests processMKISOrder in insert context with a valid Order
     */
    @IsTest
    static void testProcessMKISOrderOnInsert() {
        Order testOrder = [SELECT Id, AccountId, Status, UrlLinkStatus__c,
                                  ChargeIdentifier__c, Guild__c, Urgent__c,
                                  Observaciones__c, Type, ProviderType__c,
                                  ProviderReference__c, /* Causa__c, SubCausa__c, */
                                  OPFVTSIndicatorsPresent__c, RelatedOrder__c,
                                  CaseNumber__c, BillToContactId
                           FROM Order LIMIT 1];

        Map<Id, Order> newMap = new Map<Id, Order>{ testOrder.Id => testOrder };

        Test.setMock(HttpCalloutMock.class, new MKISElbaMock());

        Test.startTest();
        MKISElbaOrderTriggerLogic.processMKISOrder(newMap, null, true, false);
        Test.stopTest();

        System.assertNotEquals(null, testOrder.Id, 'Order should exist');
    }

    /**
     * @description Tests processMKISOrder in update context with relevant field changes
     */
    @IsTest
    static void testProcessMKISOrderOnUpdate() {
        Order testOrder = [SELECT Id, AccountId, Status, UrlLinkStatus__c,
                                  ChargeIdentifier__c, Guild__c, Urgent__c,
                                  Observaciones__c, Type, ProviderType__c,
                                  ProviderReference__c, /* Causa__c, SubCausa__c, */
                                  OPFVTSIndicatorsPresent__c, RelatedOrder__c,
                                  CaseNumber__c, BillToContactId
                           FROM Order LIMIT 1];

        Order oldOrder = testOrder.clone(true, true, true, true);
        Map<Id, Order> newMap = new Map<Id, Order>{ testOrder.Id => testOrder };
        Map<Id, Order> oldMap = new Map<Id, Order>{ testOrder.Id => oldOrder };

        Test.setMock(HttpCalloutMock.class, new MKISElbaMock());

        Test.startTest();
        MKISElbaOrderTriggerLogic.processMKISOrder(newMap, oldMap, false, true);
        Test.stopTest();

        System.assertNotEquals(null, testOrder.Id, 'Order should exist');
    }

    /**
     * @description Tests processMKISOrder with null input does not throw exceptions
     */
    @IsTest
    static void testProcessMKISOrderWithNullInput() {
        Test.startTest();
        MKISElbaOrderTriggerLogic.processMKISOrder(null, null, true, false);
        Test.stopTest();

        // No exception should be thrown
        System.assert(true, 'Null input should be handled gracefully');
    }
}