default/objects/Account/fields/Guild__c.field-meta.xml
<CustomField>
    <fullName>Guild__c</fullName>
    <label>Guild</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Guild</valueSetName>
    </valueSet>
</CustomField>

default/objects/Account/fields/SAPEntityCode__c.field-meta.xml
<CustomField>
    <fullName>SAPEntityCode__c</fullName>
    <externalId>true</externalId>
    <label>SAPEntityCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <label>Supplier</label>
</RecordType>

default/objects/AccountInformation__c/AccountInformation__c.object-meta.xml
<CustomObject>
    <label>Account Information</label>
    <nameField>
        <displayFormat>AI --{00000}</displayFormat>
        <label>Account Information</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/AccountInformation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>AccountPhones</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/AccountInformation__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AC</fullName>
                <label>WORKSHOP</label>
            </value>
            <value>
                <fullName>AG</fullName>
                <label>AGENCY</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>WORKSHOP AT</label>
            </value>
            <value>
                <fullName>BU</fullName>
                <label>OFFICE</label>
            </value>
            <value>
                <fullName>CE</fullName>
                <label>CALLCENTER</label>
            </value>
            <value>
                <fullName>DO</fullName>
                <label>HOME</label>
            </value>
            <value>
                <fullName>PC</fullName>
                <label>MOBILE</label>
            </value>
            <value>
                <fullName>PO</fullName>
                <label>MOBILE PO</label>
            </value>
            <value>
                <fullName>SC</fullName>
                <label>RECEPTION</label>
            </value>
            <value>
                <fullName>ST</fullName>
                <label>RECEPTION ST</label>
            </value>
            <value>
                <fullName>JT</fullName>
                <label>LIGNE 24/24</label>
            </value>
            <value>
                <fullName>J7</fullName>
                <label>LIGNE 7J/7</label>
            </value>
            <value>
                <fullName>RE</fullName>
                <label>RETURN</label>
            </value>
            <value>
                <fullName>AE</fullName>
                <label>AIRPORT</label>
            </value>
            <value>
                <fullName>GA</fullName>
                <label>STATION</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>OFFICE CA</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>ALPHAPAGE</label>
            </value>
            <value>
                <fullName>OP</fullName>
                <label>OPERATOR</label>
            </value>
            <value>
                <fullName>EU</fullName>
                <label>EUROSIGNAL</label>
            </value>
            <value>
                <fullName>HO</fullName>
                <label>HOSPITAL(STANDARD)</label>
            </value>
            <value>
                <fullName>CL</fullName>
                <label>HOSPITAL(STANDARD) CL</label>
            </value>
            <value>
                <fullName>S1</fullName>
                <label>EMERGENCY</label>
            </value>
            <value>
                <fullName>S2</fullName>
                <label>RESUSCITATION</label>
            </value>
            <value>
                <fullName>S3</fullName>
                <label>CARDIOLOGY</label>
            </value>
            <value>
                <fullName>S4</fullName>
                <label>ORTHOPEDIC SURGERY</label>
            </value>
            <value>
                <fullName>S5</fullName>
                <label>VISCERAL SURGERY</label>
            </value>
            <value>
                <fullName>S6</fullName>
                <label>MEDICINE</label>
            </value>
            <value>
                <fullName>S7</fullName>
                <label>PEDIATRICS</label>
            </value>
            <value>
                <fullName>S8</fullName>
                <label>MATERNITY</label>
            </value>
            <value>
                <fullName>S9</fullName>
                <label>NEUROSURGERY</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/AccountInformation__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/AccountInformation__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

default/objects/Case/fields/Urgent__c.field-meta.xml
<CustomField>
    <fullName>Urgent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Urgent</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Order/fields/ChargeIdentifier__c.field-meta.xml
<CustomField>
    <fullName>ChargeIdentifier__c</fullName>
    <externalId>true</externalId>
    <label>Charge Identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Order/fields/Guild__c.field-meta.xml
<CustomField>
    <fullName>Guild__c</fullName>
    <label>Guild</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Guild</valueSetName>
    </valueSet>
</CustomField>

default/objects/Order/fields/Observaciones__c.field-meta.xml
<CustomField>
    <fullName>Observaciones__c</fullName>
    <label>Observations</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Order/fields/ProviderType__c.field-meta.xml
<CustomField>
    <fullName>ProviderType__c</fullName>
    <label>Provider Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MU</fullName>
                <label>Multi-trade</label>
            </value>
            <value>
                <fullName>MA</fullName>
                <label>Handyman</label>
            </value>
            <value>
                <fullName>DE</fullName>
                <label>Drain Unblocking</label>
            </value>
            <value>
                <fullName>CE</fullName>
                <label>Locksmith</label>
            </value>
            <value>
                <fullName>CR</fullName>
                <label>Glazing</label>
            </value>
            <value>
                <fullName>ELBA</fullName>
                <label>Electrical</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>Carpentry</label>
            </value>
            <value>
                <fullName>PA</fullName>
                <label>Flooring (Parquet)</label>
            </value>
            <value>
                <fullName>LS</fullName>
                <label>Sanitary Ware</label>
            </value>
            <value>
                <fullName>ST</fullName>
                <label>Technical Service</label>
            </value>
            <value>
                <fullName>TC</fullName>
                <label>Boiler Technician</label>
            </value>
            <value>
                <fullName>OT</fullName>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Order/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Order/fields/Urgent__c.field-meta.xml
<CustomField>
    <fullName>Urgent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Urgent</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <displayFormat>SE - {00000}</displayFormat>
        <label>Services Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Service__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Claim</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

default/objects/Service__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Service__c/fields/Stakeholder__c.field-meta.xml
<CustomField>
    <fullName>Stakeholder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stakeholder</label>
    <referenceTo>Stakeholders__c</referenceTo>
    <relationshipName>StakeholderContacts</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Service__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

default/objects/Service__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apertura</fullName>
                <default>true</default>
                <label>Apertura</label>
            </value>
            <value>
                <fullName>Presupuestacion</fullName>
            </value>
            <value>
                <fullName>En Ejecucion de Trabajos</fullName>
            </value>
            <value>
                <fullName>Servicio Cerrado</fullName>
            </value>
            <value>
                <fullName>Cierre Parcial</fullName>
            </value>
            <value>
                <fullName>Cancelado/Anulado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Service__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Guild</valueSetName>
    </valueSet>
</CustomField>

default/objects/Stakeholders__c/Stakeholders__c.object-meta.xml
<CustomObject>
    <label>Stakeholder</label>
    <nameField>
        <label>Stakeholders Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stakeholders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/classes/PelayoOutBoundStrucuture.cls
/**
 * @description       : Base outbound structure builder for Pelayo API JSON payloads
 * @author            : Daniel Flores
 * @group             :
 * @last modified on  : 20-04-2026
 * @last modified by  : Daniel Flores
**/
public class PelayoOutBoundStrucuture {

    private static final String SUPPLIER_RECORD_TYPE = 'Supplier';

    public String idSiniestroElba;
    public String idSiniestroAseguradora;
    public String movimiento;
    public List<Encargo> encargos;

    public class Encargo {
        public String idEncargoElba;
        public String idEncargoAseguradora;
        public Date fechaEncargo;
        public Time horaEncargo;
        public String tramitadorEncargo;
        public String tipo;
        public String tipoProveedor;
        public String gremio;
        public String estado;
        public String observaciones;
        public Boolean urgente;
        public Proveedor proveedor;
        public List<Servicio> servicios;
    }

    public class Proveedor {
        public String id;
        public String nombre;
        public String email;
        public String telefono;
        public String movil;
    }

    public class Servicio {
        public String idServicio;
        public String estado;
        public String gremio;
        public String implicado;
        public String situacion;
        public String descripcion;
        public Date fechaApertura;
    }

    /*************************************** */

    public class CaseInfo {
        public String caseNumber;
        public String insurerClaimReference;
        public String claimsHandlerName;
    }

    /**
     * @description Builds the JSON payload for the Pelayo updateAssignment API from Case info, Orders, provider account data, and a movement type.
     * @param caseInfo Wrapper with Case-level identifiers.
     * @param listEncargo List of Order records (encargos) to include.
     * @param mapAccountInformation Map of provider account phone/email values keyed by Type_AccountId.
     * @param type The movement type identifier (e.g. 'AL', 'MO').
     * @return Serialized JSON string of the outbound payload.
     */
    public static String createJSON(CaseInfo caseInfo, List<Order> listEncargo, Map<String, String> mapAccountInformation, String type){

        PelayoOutBoundStrucuture body = new PelayoOutBoundStrucuture();
        body.idSiniestroElba = caseInfo.caseNumber;
        body.idSiniestroAseguradora = caseInfo.insurerClaimReference;
        body.movimiento = type;

        body.encargos = new List<Encargo>();

        for (Order encargo : listEncargo) {
            Encargo encargoBody = new Encargo();
            encargoBody.idEncargoElba = encargo.Id;
            encargoBody.idEncargoAseguradora = encargo.ChargeIdentifier__c;
            encargoBody.fechaEncargo = encargo.EffectiveDate;
            encargoBody.horaEncargo = encargo.CreatedDate.time();
            encargoBody.tramitadorEncargo = caseInfo.claimsHandlerName;
            encargoBody.tipo = encargo.Type;
            encargoBody.tipoProveedor = encargo.ProviderType__c;
            encargoBody.gremio = encargo.Guild__c;
            encargoBody.estado = encargo.Status;
            encargoBody.observaciones = encargo.Observaciones__c;
            encargoBody.urgente = encargo.Urgent__c;

            if(type != null && isSupplierOrder(encargo)) {
                Proveedor proveedorBody = new Proveedor();
                proveedorBody.id = encargo.Account.SAPEntityCode__c;
                proveedorBody.nombre = encargo.Account.Name;
                proveedorBody.email = mapAccountInformation.containsKey('Email_' + encargo.AccountId) ? mapAccountInformation.get('Email_' + encargo.AccountId) : null;
                proveedorBody.telefono = encargo.Account.Phone;
                proveedorBody.movil = mapAccountInformation.containsKey('Phone_' + encargo.AccountId) ? mapAccountInformation.get('Phone_' + encargo.AccountId) : null;
                encargoBody.proveedor = proveedorBody;
            }

            List<Servicio> listaServiciosBody = new List<Servicio>();
            for (Service__c service : encargo.Services__r) {
                Servicio servicioBody = new Servicio();
                servicioBody.idServicio = service.Name;
                servicioBody.estado = service.Status__c;
                servicioBody.gremio = service.Type__c;
                servicioBody.implicado = service.Stakeholder__r.Name;
                servicioBody.situacion = service.Status__c;
                servicioBody.descripcion = service.Description__c;
                servicioBody.fechaApertura = service.StartDate__c;
                listaServiciosBody.add(servicioBody);
            }
            encargoBody.servicios = listaServiciosBody;
            body.encargos.add(encargoBody);
        }
        return JSON.serialize(body);
    }

    /**
     * @description Queries AccountInformation__c records for the providers referenced in the given Orders and returns a map keyed by Type_AccountId.
     * @param listEncargo List of Order records whose AccountIds are used to query provider information.
     * @return Map of account information values keyed by 'Type_AccountId'.
     */
    public static Map<String, String> setMapAccountInformation(List<Order> listEncargo) {
        List<String> listProviderIds = new List<String>();
        for (Order encargo : listEncargo) {
            if (isSupplierOrder(encargo) && encargo.AccountId != null) {
                listProviderIds.add(encargo.AccountId);
            }
        }

        Map<String, String> accountInformationMap = new Map<String, String>();
        List<AccountInformation__c> listAccountInformation = [SELECT Id, Type__c, Value__c, Account__c FROM AccountInformation__c WHERE Account__c IN :listProviderIds];
        for (AccountInformation__c accountInfo : listAccountInformation) {
            accountInformationMap.put(accountInfo.Type__c + '_' + accountInfo.Account__c, accountInfo.Value__c);
        }
        return accountInformationMap;
    }

    private static Boolean isSupplierOrder(Order encargo) {
        return encargo != null
            && encargo.Account != null
            && encargo.Account.RecordType != null
            && encargo.Account.RecordType.DeveloperName == SUPPLIER_RECORD_TYPE;
    }
}