default/objects/Account/fields/Guild__c.field-meta.xml
<CustomField>
    <fullName>Guild__c</fullName>
    <label>Guild</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Guild</valueSetName>
    </valueSet>
</CustomField>

default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <label>Supplier</label>
</RecordType>

default/objects/Order/fields/AdjusterInterventionRequired__c.field-meta.xml
<CustomField>
    <fullName>AdjusterInterventionRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Adjuster Intervention Required</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Order/fields/CaseNumber__c.field-meta.xml
<CustomField>
    <fullName>CaseNumber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Order/fields/ClaimCoverage__c.field-meta.xml
<CustomField>
    <fullName>ClaimCoverage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Claim Coverage</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Order/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <label>Coverage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Covered</fullName>
            </value>
            <value>
                <fullName>Not covered</fullName>
            </value>
            <value>
                <fullName>Rejection</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Order/fields/DamageDuetoLackofMaintenance__c.field-meta.xml
<CustomField>
    <fullName>DamageDuetoLackofMaintenance__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Damage Due to Lack of Maintenance</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Order/fields/DamagePriortoDateofOccurrence__c.field-meta.xml
<CustomField>
    <fullName>DamagePriortoDateofOccurrence__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Damage Prior to Date of Occurrence</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Order/fields/DamagePriortoPolicyInception__c.field-meta.xml
<CustomField>
    <fullName>DamagePriortoPolicyInception__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Damage Prior to Policy Inception</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Order/fields/Guild__c.field-meta.xml
<CustomField>
    <fullName>Guild__c</fullName>
    <label>Guild</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Guild</valueSetName>
    </valueSet>
</CustomField>

default/objects/Order/fields/InitialDamagesLocated__c.field-meta.xml
<CustomField>
    <fullName>InitialDamagesLocated__c</fullName>
    <label>Initial Damages Located</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Order/fields/InitialDamagesRepaired__c.field-meta.xml
<CustomField>
    <fullName>InitialDamagesRepaired__c</fullName>
    <label>Initial Damages Repaired</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Order/fields/MeetsVATConditions__c.field-meta.xml
<CustomField>
    <fullName>MeetsVATConditions__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Meets VAT Conditions</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Order/fields/NoRepairReason__c.field-meta.xml
<CustomField>
    <fullName>NoRepairReason__c</fullName>
    <label>No Repair Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Compensation - Preferred Repairer</fullName>
            </value>
            <value>
                <fullName>Corrosion</fullName>
            </value>
            <value>
                <fullName>Pending repair of originating cause</fullName>
            </value>
            <value>
                <fullName>Need for intervention of other trades before continuing work</fullName>
            </value>
            <value>
                <fullName>No coverage</fullName>
            </value>
            <value>
                <fullName>Insured requests compensation. Trusted repairer</fullName>
            </value>
            <value>
                <fullName>Pending tools for localization</fullName>
            </value>
            <value>
                <fullName>Restricted hours for noise</fullName>
            </value>
            <value>
                <fullName>Adverse weather conditions for repair</fullName>
            </value>
            <value>
                <fullName>Client request</fullName>
            </value>
            <value>
                <fullName>Expert assessment intervention required</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Lack of Maintenance</fullName>
                <isActive>false</isActive>
                <label>Lack of Maintenance</label>
            </value>
            <value>
                <fullName>Pending Material</fullName>
                <isActive>false</isActive>
                <label>Pending Material</label>
            </value>
            <value>
                <fullName>Schedules</fullName>
                <isActive>false</isActive>
                <label>Schedules</label>
            </value>
            <value>
                <fullName>Specialist Required</fullName>
                <isActive>false</isActive>
                <label>Specialist Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Order/fields/Observaciones__c.field-meta.xml
<CustomField>
    <fullName>Observaciones__c</fullName>
    <label>Observations</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Order/fields/OngoingDamage__c.field-meta.xml
<CustomField>
    <fullName>OngoingDamage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ongoing Damage</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Order/fields/OperatorAssessment__c.field-meta.xml
<CustomField>
    <fullName>OperatorAssessment__c</fullName>
    <label>Operator Assessment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/Order/fields/OperatorDescription__c.field-meta.xml
<CustomField>
    <fullName>OperatorDescription__c</fullName>
    <label>Operator Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/Order/fields/OPFVTSIndicatorsPresent__c.field-meta.xml
<CustomField>
    <fullName>OPFVTSIndicatorsPresent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OPF/VTS Indicators Present</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Order/fields/OriginIdentification__c.field-meta.xml
<CustomField>
    <fullName>OriginIdentification__c</fullName>
    <label>Origin Identification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic activities</fullName>
            </value>
            <value>
                <fullName>Appliance older than 10 years</fullName>
            </value>
            <value>
                <fullName>Telephony, image, sound and IT equipment</fullName>
            </value>
            <value>
                <fullName>Drain blockage with damage</fullName>
            </value>
            <value>
                <fullName>Manhole or well blockage</fullName>
            </value>
            <value>
                <fullName>Community blockage</fullName>
            </value>
            <value>
                <fullName>Drain blockage without damage</fullName>
            </value>
            <value>
                <fullName>Terrace blockage</fullName>
            </value>
            <value>
                <fullName>Blockage, cleaning, obstructions</fullName>
            </value>
            <value>
                <fullName>Generic breakdown</fullName>
            </value>
            <value>
                <fullName>Mechanical and electrical breakdown</fullName>
            </value>
            <value>
                <fullName>Glass railings and steps</fullName>
            </value>
            <value>
                <fullName>Electric bicycle, electric scooter</fullName>
            </value>
            <value>
                <fullName>Paving blocks</fullName>
            </value>
            <value>
                <fullName>Fall of aerolites/aircraft</fullName>
            </value>
            <value>
                <fullName>Falling trees, poles and antennas</fullName>
            </value>
            <value>
                <fullName>Capillarity</fullName>
            </value>
            <value>
                <fullName>Accidental cause: fall, impact and liquid spill</fullName>
            </value>
            <value>
                <fullName>Animal collision</fullName>
            </value>
            <value>
                <fullName>Vehicle collision</fullName>
            </value>
            <value>
                <fullName>Condensation</fullName>
            </value>
            <value>
                <fullName>Corrosion</fullName>
            </value>
            <value>
                <fullName>Corrosion, oxidation</fullName>
            </value>
            <value>
                <fullName>Short circuit in home installation</fullName>
            </value>
            <value>
                <fullName>Door glass</fullName>
            </value>
            <value>
                <fullName>Window glass</fullName>
            </value>
            <value>
                <fullName>Furniture glass/mirrors and methacrylates</fullName>
            </value>
            <value>
                <fullName>Home glass/mirrors and methacrylates</fullName>
            </value>
            <value>
                <fullName>Construction defect</fullName>
            </value>
            <value>
                <fullName>Aesthetic defect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Order/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Reasons</valueSetName>
    </valueSet>
</CustomField>

default/objects/Order/fields/ReasonforAdjusterIntervention__c.field-meta.xml
<CustomField>
    <fullName>ReasonforAdjusterIntervention__c</fullName>
    <label>Reason for Adjuster Intervention</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer request</fullName>
            </value>
            <value>
                <fullName>Difficulty locating origin</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>Based on damage amount</fullName>
            </value>
            <value>
                <fullName>Content damage</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Order/fields/Rejection__c.field-meta.xml
<CustomField>
    <fullName>Rejection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Rejection</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Order/fields/RelatedOrder__c.field-meta.xml
<CustomField>
    <fullName>RelatedOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Order/fields/SubReason__c.field-meta.xml
<CustomField>
    <fullName>SubReason__c</fullName>
    <label>Sub-Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SubReasons</valueSetName>
    </valueSet>
</CustomField>

default/objects/Order/fields/TotalBudgetAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalBudgetAmount__c</fullName>
    <label>Total Budget Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

default/objects/Order/fields/Urgent__c.field-meta.xml
<CustomField>
    <fullName>Urgent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Urgent</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Order/fields/UrlLinkStatus__c.field-meta.xml
<CustomField>
    <fullName>UrlLinkStatus__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Urlink Status</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Order/fields/VisitCompleted__c.field-meta.xml
<CustomField>
    <fullName>VisitCompleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visit Completed</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Order/fields/VisitDateTime__c.field-meta.xml
<CustomField>
    <fullName>VisitDateTime__c</fullName>
    <label>Visit Date Time</label>
    <type>DateTime</type>
</CustomField>

default/objects/Order/fields/VisitNotCompletedReason__c.field-meta.xml
<CustomField>
    <fullName>VisitNotCompletedReason__c</fullName>
    <label>Visit Not Completed Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Appointment Rescheduled</fullName>
            </value>
            <value>
                <fullName>By Policyholder</fullName>
            </value>
            <value>
                <fullName>By Responsible Party</fullName>
            </value>
            <value>
                <fullName>By Claimant</fullName>
            </value>
            <value>
                <fullName>Appointment Cancelled</fullName>
            </value>
            <value>
                <fullName>By Platform</fullName>
            </value>
            <value>
                <fullName>By Insurance Company</fullName>
            </value>
            <value>
                <fullName>By Adjuster</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Order/fields/VisitType__c.field-meta.xml
<CustomField>
    <fullName>VisitType__c</fullName>
    <label>Visit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Person</fullName>
            </value>
            <value>
                <fullName>Video Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/classes/MKISElbaOrderTriggerLogic.cls
/**
 * @description       : MKIS-specific Order trigger logic.
 *                      Determines when to call MKIS ELBA API for Create/Update Service and Create Contact.
 * @author            : Daniel Flores
 * @group             : MKIS Integration
 * @last modified on  : 07-05-2026
 * @last modified by  : Daniel Flores
**/
public without sharing class MKISElbaOrderTriggerLogic {
    // Nome do utilizador de integração MKIS (display name, estável entre ambientes)
    private static final String MKIS_INTEGRATION_USER_NAME = 'MKIS Integration';

    /**
    * @description Processes Orders in the trigger context for MKIS integration.
    * @param newMap New Order records map
    * @param oldMap Old Order records map
    * @param isInsert Whether this is an insert operation
    * @param isUpdate Whether this is an update operation
    **/
    public static void processMKISOrder(
        Map<Id, Order> newMap,
        Map<Id, Order> oldMap,
        Boolean isInsert,
        Boolean isUpdate
    ) {
        if (newMap == null || newMap.isEmpty()) return;

        Map<Id, Account> accountsById = getAccountsById(newMap.values());

        List<Id> createServiceOrderIds = new List<Id>();
        List<Id> updateServiceOrderIds = new List<Id>();
        List<Id> createContactOrderIds = new List<Id>();

        for (Order newOrder : newMap.values()) {
            Boolean newAccountIsSupplier = isSupplierAccount(newOrder, accountsById);

            if (isInsert && newAccountIsSupplier) {
                
                createServiceOrderIds.add(newOrder.Id);
            }

            if (isUpdate) {
                Order oldOrder = oldMap != null ? oldMap.get(newOrder.Id) : null;
                Boolean accountChanged = oldOrder != null && newOrder.AccountId != oldOrder.AccountId;

                if (/* accountChanged && */ newAccountIsSupplier && newOrder.UrlLinkStatus__c != true) {
                    createServiceOrderIds.add(newOrder.Id);
                }

                // UPDATE SERVICE: Quando um encargo é atualizado
                if (newAccountIsSupplier && newOrder.UrlLinkStatus__c == true && hasRelevantServiceFieldsChanged(newOrder, oldOrder)) {
                    updateServiceOrderIds.add(newOrder.Id);
                }

                // CREATE CONTACT: Quando certos campos são atualizados
                // Não chamar endpoint de contacts se o utilizador for MKIS Integration
                if (UserInfo.getName() != MKIS_INTEGRATION_USER_NAME) {
                    if (MKISElbaContactHandler.hasContactFieldsChanged(newOrder, oldOrder)) {
                        createContactOrderIds.add(newOrder.Id);
                    }
                }
            }
        }
        System.debug('Quantos encargos estão aqui:' + createServiceOrderIds.size());
        if (!createServiceOrderIds.isEmpty() && !System.isFuture() && !System.isBatch()) {

            System.debug('Entrei aqui para depurar');
            List<Id> validCreateServiceOrderIds = CreateNewServiceController.filterOrdersWithMandatoryFields(createServiceOrderIds);
            if (!validCreateServiceOrderIds.isEmpty()) {
                System.debug('Entrei aqui para depurar 2');
                if (UserInfo.getName() != MKIS_INTEGRATION_USER_NAME) {
                    MKISElbaServiceHandler.createServiceAsync(validCreateServiceOrderIds);
                }
            }
        }

        if (!updateServiceOrderIds.isEmpty() && !System.isFuture() && !System.isBatch()) {
            if (UserInfo.getName() != MKIS_INTEGRATION_USER_NAME) {
                MKISElbaServiceHandler.updateServiceAsync(updateServiceOrderIds);
            }
            
        }

        if (!createContactOrderIds.isEmpty() && !System.isFuture() && !System.isBatch()) {
            if (UserInfo.getName() != MKIS_INTEGRATION_USER_NAME) {
                MKISElbaContactHandler.createContactAsync(createContactOrderIds);
            }
        }
    }

    /**
    * @description Checks if any service-relevant fields have changed between old and new Order.
    * @param newOrder The new Order record
    * @param oldOrder The old Order record
    * @return Boolean true if relevant fields changed
    **/
    private static Boolean hasRelevantServiceFieldsChanged(Order newOrder, Order oldOrder) {
        if (oldOrder == null) {
            return false;
        }

        return newOrder.AccountId != oldOrder.AccountId
            || newOrder.BillToContactId != oldOrder.BillToContactId
            || newOrder.CaseNumber__c != oldOrder.CaseNumber__c
            || newOrder.RelatedOrder__c != oldOrder.RelatedOrder__c
            // Policy / insured
            || newOrder.Urgent__c != oldOrder.Urgent__c
            // Contact
            // (driven by BillToContactId above)
            // Dates
            // (driven by CaseNumber__c above)
            // Optional details
            || newOrder.Observaciones__c != oldOrder.Observaciones__c
            || newOrder.Reason__c != oldOrder.Reason__c
            || newOrder.SubReason__c != oldOrder.SubReason__c
            || newOrder.Guild__c != oldOrder.Guild__c
            || newOrder.Coverage__c != oldOrder.Coverage__c
            // Integer flags
            || newOrder.OPFVTSIndicatorsPresent__c != oldOrder.OPFVTSIndicatorsPresent__c
            // Visit fields
            || newOrder.VisitCompleted__c != oldOrder.VisitCompleted__c
            || newOrder.VisitNotCompletedReason__c != oldOrder.VisitNotCompletedReason__c
            || newOrder.VisitDateTime__c != oldOrder.VisitDateTime__c
            || newOrder.VisitType__c != oldOrder.VisitType__c
            || newOrder.OperatorDescription__c != oldOrder.OperatorDescription__c
            // Damage assessment flags
            || newOrder.OriginIdentification__c != oldOrder.OriginIdentification__c
            || newOrder.DamagePriortoPolicyInception__c != oldOrder.DamagePriortoPolicyInception__c
            || newOrder.DamagePriortoDateofOccurrence__c != oldOrder.DamagePriortoDateofOccurrence__c
            || newOrder.OngoingDamage__c != oldOrder.OngoingDamage__c
            || newOrder.DamageDuetoLackofMaintenance__c != oldOrder.DamageDuetoLackofMaintenance__c
            || newOrder.ClaimCoverage__c != oldOrder.ClaimCoverage__c
            || newOrder.Rejection__c != oldOrder.Rejection__c
            || newOrder.OperatorAssessment__c != oldOrder.OperatorAssessment__c
            || newOrder.MeetsVATConditions__c != oldOrder.MeetsVATConditions__c
            || newOrder.InitialDamagesLocated__c != oldOrder.InitialDamagesLocated__c
            || newOrder.InitialDamagesRepaired__c != oldOrder.InitialDamagesRepaired__c
            || newOrder.NoRepairReason__c != oldOrder.NoRepairReason__c
            || newOrder.AdjusterInterventionRequired__c != oldOrder.AdjusterInterventionRequired__c
            || newOrder.ReasonforAdjusterIntervention__c != oldOrder.ReasonforAdjusterIntervention__c
            // Budget / totals
            || newOrder.TotalBudgetAmount__c != oldOrder.TotalBudgetAmount__c;
    }

    /**
    * @description Queries Accounts related to the given Orders and returns them in a map by Id.
    * @param orders List of Order records
    * @return Map of Account Id to Account record
    **/
    private static Map<Id, Account> getAccountsById(List<Order> orders) {
        Set<Id> accountIds = new Set<Id>();
        for (Order ord : orders) {
            if (ord.AccountId != null) {
                accountIds.add(ord.AccountId);
            }
        }

        if (accountIds.isEmpty()) {
            return new Map<Id, Account>();
        }

        return new Map<Id, Account>([
            SELECT Id, RecordType.DeveloperName
            FROM Account
            WHERE Id IN :accountIds
        ]);
    }

    /**
    * @description Determines whether the Account associated with the Order has a Supplier record type.
    * @param ord The Order record
    * @param accountsById Map of Account Id to Account record
    * @return Boolean true if the related Account is a Supplier
    **/
    private static Boolean isSupplierAccount(Order ord, Map<Id, Account> accountsById) {
        if (ord == null || ord.AccountId == null || accountsById == null) {
            return false;
        }

        Account relatedAccount = accountsById.get(ord.AccountId);
        return relatedAccount != null && relatedAccount.RecordType != null && relatedAccount.RecordType.DeveloperName == 'Supplier';
    }
}