default/objects/Account/fields/Guild__c.field-meta.xml
<CustomField>
    <fullName>Guild__c</fullName>
    <label>Guild</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Guild</valueSetName>
    </valueSet>
</CustomField>

default/objects/Case/fields/ClaimsHandlerName__c.field-meta.xml
<CustomField>
    <fullName>ClaimsHandlerName__c</fullName>
    <label>Claims Handler Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

default/objects/Case/fields/InsurerClaimReference__c.field-meta.xml
<CustomField>
    <fullName>InsurerClaimReference__c</fullName>
    <externalId>true</externalId>
    <label>Insurer Claim Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Case/fields/Urgent__c.field-meta.xml
<CustomField>
    <fullName>Urgent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Urgent</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Order/fields/CaseNumber__c.field-meta.xml
<CustomField>
    <fullName>CaseNumber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Order/fields/ChargeIdentifier__c.field-meta.xml
<CustomField>
    <fullName>ChargeIdentifier__c</fullName>
    <externalId>true</externalId>
    <label>Charge Identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Order/fields/Guild__c.field-meta.xml
<CustomField>
    <fullName>Guild__c</fullName>
    <label>Guild</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Guild</valueSetName>
    </valueSet>
</CustomField>

default/objects/Order/fields/Observaciones__c.field-meta.xml
<CustomField>
    <fullName>Observaciones__c</fullName>
    <label>Observations</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Order/fields/ProviderReference__c.field-meta.xml
<CustomField>
    <fullName>ProviderReference__c</fullName>
    <label>Provider Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Order/fields/ProviderType__c.field-meta.xml
<CustomField>
    <fullName>ProviderType__c</fullName>
    <label>Provider Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MU</fullName>
                <label>Multi-trade</label>
            </value>
            <value>
                <fullName>MA</fullName>
                <label>Handyman</label>
            </value>
            <value>
                <fullName>DE</fullName>
                <label>Drain Unblocking</label>
            </value>
            <value>
                <fullName>CE</fullName>
                <label>Locksmith</label>
            </value>
            <value>
                <fullName>CR</fullName>
                <label>Glazing</label>
            </value>
            <value>
                <fullName>ELBA</fullName>
                <label>Electrical</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>Carpentry</label>
            </value>
            <value>
                <fullName>PA</fullName>
                <label>Flooring (Parquet)</label>
            </value>
            <value>
                <fullName>LS</fullName>
                <label>Sanitary Ware</label>
            </value>
            <value>
                <fullName>ST</fullName>
                <label>Technical Service</label>
            </value>
            <value>
                <fullName>TC</fullName>
                <label>Boiler Technician</label>
            </value>
            <value>
                <fullName>OT</fullName>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Order/fields/Urgent__c.field-meta.xml
<CustomField>
    <fullName>Urgent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Urgent</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <displayFormat>SE - {00000}</displayFormat>
        <label>Services Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Service__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Claim</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

default/objects/Service__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Service__c/fields/Stakeholder__c.field-meta.xml
<CustomField>
    <fullName>Stakeholder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stakeholder</label>
    <referenceTo>Stakeholders__c</referenceTo>
    <relationshipName>StakeholderContacts</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Service__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

default/objects/Service__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apertura</fullName>
                <default>true</default>
                <label>Apertura</label>
            </value>
            <value>
                <fullName>Presupuestacion</fullName>
            </value>
            <value>
                <fullName>En Ejecucion de Trabajos</fullName>
            </value>
            <value>
                <fullName>Servicio Cerrado</fullName>
            </value>
            <value>
                <fullName>Cierre Parcial</fullName>
            </value>
            <value>
                <fullName>Cancelado/Anulado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Service__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Guild</valueSetName>
    </valueSet>
</CustomField>

default/objects/Stakeholders__c/Stakeholders__c.object-meta.xml
<CustomObject>
    <label>Stakeholder</label>
    <nameField>
        <label>Stakeholders Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stakeholders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/classes/IntegrationsExtensionClass.cls
/**
 * @description       : Callable extension class for routing integration actions to appropriate handlers
 * @author            : Daniel Flores
 * @group             :
 * @last modified on  : 03-03-2026
 * @last modified by  : Daniel Flores
 **/
public with sharing class IntegrationsExtensionClass implements Callable {
	/**
	 * @description Routes the given action to the appropriate integration handler and executes it
	 * @param action The action name identifying which integration to invoke
	 * @param params Map of parameters required by the target integration handler
	 * @return The result of the integration action execution
	 */
	public Object call(String action, Map<String, Object> params) {
		switch on action {
			when 'PelayoWebServiceController.assignEncargoPelayoService' {
				return call('assignEncargoPelayoService', params);
			}
			when 'assignEncargoPelayoService' {
				// type e orderId (pode ser lista separada por vírgula)
				String type = (String) params.get('type');
				String orderIdStr = (String) params.get('orderId');
				List<String> orderIds = new List<String>();
				if (orderIdStr != null) {
					for (String rawId : orderIdStr.split(',')) {
						if (String.isBlank(rawId)) continue;
						String cleaned = rawId.trim();
						if (String.isBlank(cleaned)) continue;
						orderIds.add(cleaned);
					}
				}
				if (String.isBlank(type)) {
					throw new ExtensionMalformedCallException('Missing parameter: type');
				}
				if (orderIds.isEmpty()) {
					throw new ExtensionMalformedCallException('Missing parameter: orderId');
				}
				List<Order> orders = new List<Order>();
				if (!orderIds.isEmpty()) {
					orders = [
						SELECT
							Id,
							CaseNumber__c,
							CaseNumber__r.CaseNumber,
							CaseNumber__r.InsurerClaimReference__c,
							CaseNumber__r.ClaimsHandlerName__c,
							AccountId,
							Account.Name,
							Account.Phone,
							OrderNumber,
							ChargeIdentifier__c,
							CreatedDate,
							EffectiveDate,
							Type,
							ProviderType__c,
							Guild__c,
							Status,
							Observaciones__c,
							Urgent__c,
							ProviderReference__c,
							(
								SELECT
									Name,
									Status__c,
									Type__c,
									Stakeholder__c,
									Stakeholder__r.Name,
									Description__c,
									StartDate__c
								FROM Services__r
							)
						FROM Order
						WHERE Id IN :orderIds
					];
				}
				if (orders.isEmpty()) {
					throw new ExtensionMalformedCallException('No Orders found for provided orderId(s).');
				}
				PelayoWebServiceController.assignEncargoPelayoService(null, orders, type);
				return 'assignEncargoPelayoService';
			}
			
			
			when else {
				throw new ExtensionMalformedCallException(
					'Method not implemented'
				);
			}
		}
	}

	public class ExtensionMalformedCallException extends Exception {
	}
}