default/objects/ContentVersion/fields/DocumentType__c.field-meta.xml
<CustomField>
    <fullName>DocumentType__c</fullName>
    <label>Documental Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>DocumentPhase__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>T01001</fullName>
                <label>Facturas asegurado</label>
            </value>
            <value>
                <fullName>T01002</fullName>
                <label>Presupuesto asegurado</label>
            </value>
            <value>
                <fullName>2008003</fullName>
                <label>Facturas abogados</label>
            </value>
            <value>
                <fullName>T01003</fullName>
                <label>Minutas perito</label>
            </value>
            <value>
                <fullName>T01004</fullName>
                <label>Facturas reparador</label>
            </value>
            <value>
                <fullName>T01005</fullName>
                <label>Facturas Otros Colaboradores</label>
            </value>
            <value>
                <fullName>T01006</fullName>
                <label>Justificantes de pago</label>
            </value>
            <value>
                <fullName>T02001</fullName>
                <label>Informes Meteorología</label>
            </value>
            <value>
                <fullName>T02002</fullName>
                <label>Escrituras vivienda</label>
            </value>
            <value>
                <fullName>T02003</fullName>
                <label>Denuncias Robo/Actos Vandálicos</label>
            </value>
            <value>
                <fullName>T02004</fullName>
                <label>Fotografías del asegurado</label>
            </value>
            <value>
                <fullName>T02005</fullName>
                <label>Declaración del contrario</label>
            </value>
            <value>
                <fullName>T02006</fullName>
                <label>Otra documentación</label>
            </value>
            <value>
                <fullName>T03001</fullName>
                <label>Albaranes</label>
            </value>
            <value>
                <fullName>T03002</fullName>
                <label>Fotografias colaborador</label>
            </value>
            <value>
                <fullName>T03003</fullName>
                <label>Informe pericial Diversos</label>
            </value>
            <value>
                <fullName>T03004</fullName>
                <label>Ordenes de trabajo</label>
            </value>
            <value>
                <fullName>T03005</fullName>
                <label>Parte de trabajo</label>
            </value>
            <value>
                <fullName>T05001</fullName>
                <label>Documentos Varios VTS</label>
            </value>
            <value>
                <fullName>T05002</fullName>
                <label>informe investigación VTS</label>
            </value>
            <value>
                <fullName>T05003</fullName>
                <label>Mail VTS</label>
            </value>
            <value>
                <fullName>T05004</fullName>
                <label>Llamadas VTS</label>
            </value>
            <value>
                <fullName>T05005</fullName>
                <label>Videos VTS</label>
            </value>
            <value>
                <fullName>T05006</fullName>
                <label>Fotografías VTS</label>
            </value>
            <value>
                <fullName>T06001</fullName>
                <label>Comunicaciones de clientes</label>
            </value>
            <value>
                <fullName>T06003</fullName>
                <label>Comunicaciones a cliente Propuesta indemnización</label>
            </value>
            <value>
                <fullName>T06004</fullName>
                <label>Comunicaciones Enviadas</label>
            </value>
            <value>
                <fullName>T06005</fullName>
                <label>emails internos</label>
            </value>
            <value>
                <fullName>T06006</fullName>
                <label>Reclamaciones de clientes</label>
            </value>
            <value>
                <fullName>T06007</fullName>
                <label>Incidencias/Reclamaciones GISS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/classes/PicklistDependencyHelper.cls
/**
 * @description Helper class para gerir dependências entre campos picklist
 * @author Daniel Flores
 * @group Utilities
 */
public class PicklistDependencyHelper {

    public class PicklistInfo {
        @AuraEnabled public Map<String, List<String>> dependentValues = new Map<String, List<String>>();
        @AuraEnabled public List<String> allControllingValues = new List<String>();
    }

    /**
     * @description Retorna os valores dependentes para cada valor controlador
     * @param objApiName Nome API do objeto (ex: 'ContentVersion')
     * @param controllingFieldApiName Nome API do campo controlador (ex: 'FaseDocumental__c')
     * @param dependentFieldApiName Nome API do campo dependente (ex: 'DocumentType__c')
     * @return PicklistInfo com mapa de dependências e valores do controlador
     */
    public static PicklistInfo getDependentValues(String objApiName, String controllingFieldApiName, String dependentFieldApiName) {
        PicklistInfo info = new PicklistInfo();
        
        try {
            Map<String, Schema.SObjectField> fieldMap = Schema.getGlobalDescribe()
                .get(objApiName)
                .getDescribe()
                .fields
                .getMap();
            
            Schema.DescribeFieldResult controllingFieldDesc = fieldMap.get(controllingFieldApiName).getDescribe();
            Schema.DescribeFieldResult dependentFieldDesc = fieldMap.get(dependentFieldApiName).getDescribe();

            List<Schema.PicklistEntry> controllingValues = controllingFieldDesc.getPicklistValues();
            List<Schema.PicklistEntry> dependentValues = dependentFieldDesc.getPicklistValues();

            // Iterar através dos valores controladores
            for (Integer controllingIndex = 0; controllingIndex < controllingValues.size(); controllingIndex++) {
                Schema.PicklistEntry controllingEntry = controllingValues[controllingIndex];
                String controllingValue = controllingEntry.getValue();
                
                info.allControllingValues.add(controllingValue);
                List<String> validDependentValues = new List<String>();

                // Se não há método getValidFor disponível, retornar todos os valores ativos
                // Esta é a abordagem fallback quando não há dependências configuradas no metadata
                for (Integer dependentIndex = 0; dependentIndex < dependentValues.size(); dependentIndex++) {
                    Schema.PicklistEntry dependentEntry = dependentValues[dependentIndex];
                    
                    if (dependentEntry.isActive()) {
                        validDependentValues.add(dependentEntry.getValue());
                        System.debug('Controlador: ' + controllingValue + 
                                   ', Dependente: ' + dependentEntry.getValue());
                    }
                }

                info.dependentValues.put(controllingValue, validDependentValues);
                System.debug('Valores válidos para ' + controllingValue + ': ' + validDependentValues.size());
            }
        } catch (Exception e) {
            System.debug('Erro ao obter dependências de picklist: ' + e.getMessage());
            System.debug('Stack: ' + e.getStackTraceString());
        }

        return info;
    }

    /**
     * @description Retorna os valores dependentes válidos para um valor controlador específico
     * @param objApiName Nome API do objeto
     * @param controllingFieldApiName Nome API do campo controlador
     * @param dependentFieldApiName Nome API do campo dependente
     * @param controllingValue Valor selecionado do controlador
     * @return Lista de valores dependentes válidos
     */
    public static List<String> getDependentValuesForControlling(
        String objApiName,
        String controllingFieldApiName,
        String dependentFieldApiName,
        String controllingValue
    ) {
        PicklistInfo info = getDependentValues(objApiName, controllingFieldApiName, dependentFieldApiName);
        
        if (info.dependentValues.containsKey(controllingValue)) {
            return info.dependentValues.get(controllingValue);
        }
        
        return new List<String>();
    }
}