default/objects/Case/fields/AssistanceService__c.field-meta.xml
<CustomField>
    <fullName>AssistanceService__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Assistance Service</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Case/fields/ClaimantDescription__c.field-meta.xml
<CustomField>
    <fullName>ClaimantDescription__c</fullName>
    <label>Claimant Description</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AS</fullName>
                <label>Insured</label>
            </value>
            <value>
                <fullName>CY</fullName>
                <label>Spouse</label>
            </value>
            <value>
                <fullName>HI</fullName>
                <label>Child</label>
            </value>
            <value>
                <fullName>ME</fullName>
                <label>Mediator</label>
            </value>
            <value>
                <fullName>OF</fullName>
                <label>Office</label>
            </value>
            <value>
                <fullName>FA</fullName>
                <label>Family</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Case/fields/ClaimantName__c.field-meta.xml
<CustomField>
    <fullName>ClaimantName__c</fullName>
    <label>Claimant Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

default/objects/Case/fields/ClaimDate__c.field-meta.xml
<CustomField>
    <fullName>ClaimDate__c</fullName>
    <label>Claim Date</label>
    <type>Date</type>
</CustomField>

default/objects/Case/fields/ClaimTypeIdentifier__c.field-meta.xml
<CustomField>
    <fullName>ClaimTypeIdentifier__c</fullName>
    <label>Claim Type Identifier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RE</fullName>
                <label>Repairable</label>
            </value>
            <value>
                <fullName>IN</fullName>
                <label>Compensable</label>
            </value>
            <value>
                <fullName>MX</fullName>
                <label>Mixed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Case/fields/CurrentProvisionAmount__c.field-meta.xml
<CustomField>
    <fullName>CurrentProvisionAmount__c</fullName>
    <label>Current Provision Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

default/objects/Case/fields/DamagesIncurred__c.field-meta.xml
<CustomField>
    <fullName>DamagesIncurred__c</fullName>
    <label>Damages Incurred</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0001</fullName>
                <label>ACCIDENTE</label>
            </value>
            <value>
                <fullName>0002</fullName>
                <label>ACCIDENTE  IN ITINERE</label>
            </value>
            <value>
                <fullName>0003</fullName>
                <label>ACCIDENTE DE CIRCULACION</label>
            </value>
            <value>
                <fullName>0004</fullName>
                <label>ACCIDENTE DENTRO DEL ESTADIO</label>
            </value>
            <value>
                <fullName>0005</fullName>
                <label>ACCIDENTE DEPORTIVO</label>
            </value>
            <value>
                <fullName>0006</fullName>
                <label>ACCIDENTE DOMESTICO</label>
            </value>
            <value>
                <fullName>0007</fullName>
                <label>ACCIDENTE EN GUARDERIA</label>
            </value>
            <value>
                <fullName>0008</fullName>
                <label>ACCIDENTE EN TRANSPORTE</label>
            </value>
            <value>
                <fullName>0009</fullName>
                <label>ACCIDENTE EXTRAPROFESIONAL</label>
            </value>
            <value>
                <fullName>0010</fullName>
                <label>ACCIDENTE FUERA DEL ESTADIO</label>
            </value>
            <value>
                <fullName>0011</fullName>
                <label>ACCIDENTE LABORAL</label>
            </value>
            <value>
                <fullName>0012</fullName>
                <label>ACCIDENTE MOTICICLETAS</label>
            </value>
            <value>
                <fullName>0013</fullName>
                <label>ACCIDENTE NO PROFESIONAL</label>
            </value>
            <value>
                <fullName>0014</fullName>
                <label>ACCIDENTE PROFESIONAL</label>
            </value>
            <value>
                <fullName>0015</fullName>
                <label>ACCTE CIRCUL DURANTE DESPLAZAMIENTO EN VEHICULOS</label>
            </value>
            <value>
                <fullName>0016</fullName>
                <label>ACTOS VANDALICOS POR EL INQULINO</label>
            </value>
            <value>
                <fullName>0017</fullName>
                <label>ACUARIOS</label>
            </value>
            <value>
                <fullName>0018</fullName>
                <label>ADQUISICION  DE ENSERES</label>
            </value>
            <value>
                <fullName>0019</fullName>
                <label>AEROTERMIA</label>
            </value>
            <value>
                <fullName>0020</fullName>
                <label>AIRE ACONDICIONADO</label>
            </value>
            <value>
                <fullName>0021</fullName>
                <label>AISLAMIENTO DE VENTANAS Y SIMILARES</label>
            </value>
            <value>
                <fullName>0022</fullName>
                <label>ALARMA</label>
            </value>
            <value>
                <fullName>0023</fullName>
                <label>ALIMENTOS REFRIGERADOS</label>
            </value>
            <value>
                <fullName>0024</fullName>
                <label>ALQUILER DE VIVIENDAS</label>
            </value>
            <value>
                <fullName>0025</fullName>
                <label>ANCLAJE DE SANITARIOS</label>
            </value>
            <value>
                <fullName>0026</fullName>
                <label>ANIMALES DOMESTICOS</label>
            </value>
            <value>
                <fullName>0027</fullName>
                <label>ANTENA COLECTIVA</label>
            </value>
            <value>
                <fullName>0028</fullName>
                <label>ANTENA PARTICULAR</label>
            </value>
            <value>
                <fullName>0029</fullName>
                <label>ARBOLEDA Y JARDINES</label>
            </value>
            <value>
                <fullName>0030</fullName>
                <label>ASCENSOR</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Case/fields/Deductible__c.field-meta.xml
<CustomField>
    <fullName>Deductible__c</fullName>
    <label>Deductible</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

default/objects/Case/fields/DeductibleUsed__c.field-meta.xml
<CustomField>
    <fullName>DeductibleUsed__c</fullName>
    <label>Deductible Used</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

default/objects/Case/fields/ExponentialQuadrant__c.field-meta.xml
<CustomField>
    <fullName>ExponentialQuadrant__c</fullName>
    <label>Exponential Quadrant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CA</fullName>
                <label>Catastrophe</label>
            </value>
            <value>
                <fullName>PR</fullName>
                <label>Problem</label>
            </value>
            <value>
                <fullName>MO</fullName>
                <label>Injury</label>
            </value>
            <value>
                <fullName>IN</fullName>
                <label>Inconvenience</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Case/fields/GrandAccount__c.field-meta.xml
<CustomField>
    <fullName>GrandAccount__c</fullName>
    <label>Grand Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SLA</fullName>
            </value>
            <value>
                <fullName>PLYO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Case/fields/IncidentDate__c.field-meta.xml
<CustomField>
    <fullName>IncidentDate__c</fullName>
    <label>Incident Date</label>
    <type>Date</type>
</CustomField>

default/objects/Case/fields/InsurerClaimReference__c.field-meta.xml
<CustomField>
    <fullName>InsurerClaimReference__c</fullName>
    <externalId>true</externalId>
    <label>Insurer Claim Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Case/fields/QuestionnaireComments__c.field-meta.xml
<CustomField>
    <fullName>QuestionnaireComments__c</fullName>
    <label>Questionnaire / Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/Case/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Reasons</valueSetName>
    </valueSet>
</CustomField>

default/objects/Case/fields/SituationType__c.field-meta.xml
<CustomField>
    <fullName>SituationType__c</fullName>
    <label>Situation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AP</fullName>
                <label>Proposal/Opening</label>
            </value>
            <value>
                <fullName>RZ</fullName>
                <label>Rejection</label>
            </value>
            <value>
                <fullName>EC</fullName>
                <label>In progress</label>
            </value>
            <value>
                <fullName>CE</fullName>
                <label>Operational closure</label>
            </value>
            <value>
                <fullName>FI</fullName>
                <label>Completed</label>
            </value>
            <value>
                <fullName>AN</fullName>
                <label>Cancelled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Case/fields/SubReason__c.field-meta.xml
<CustomField>
    <fullName>SubReason__c</fullName>
    <label>Sub-Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Reason__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SubReasons</valueSetName>
    </valueSet>
</CustomField>

default/objects/Case/fields/Urgent__c.field-meta.xml
<CustomField>
    <fullName>Urgent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Urgent</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Case/fields/VitalOrganAffected__c.field-meta.xml
<CustomField>
    <fullName>VitalOrganAffected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Vital Organ Affected</label>
    <type>Checkbox</type>
</CustomField>

default/classes/PelayoUpdateClaimTriggerLogic.cls
/**
 * @description       : Determines when to invoke Pelayo updateClaim based on changes.
 * @author            : Daniel Flores
 * @group             :
 * @last modified on  : 18-03-2026
 * @last modified by  : Daniel Flores
**/
public without sharing class PelayoUpdateClaimTriggerLogic {

    @TestVisible
    public static Boolean bypassExternalActions = false;
    public static Boolean enableCalloutsInTests = false;

    private static final String PELAYO_ACCOUNT_CODE = 'PLYO';
    private static final String PELAYO_INTEGRATION_USER_NAME = 'Pelayo Integration';

    @TestVisible
    static Boolean treatCurrentUserAsIntegrationUser;

    private static Boolean cachedIsIntegrationUser;

    /**
     * @description Evaluates Case records from trigger context, identifies Pelayo cases with relevant field changes, and enqueues updateClaim callouts for affected Case Ids.
     * @param newMap Map of new Case records from Trigger.newMap
     * @param oldMap Map of old Case records from Trigger.oldMap (null on insert)
     * @param isInsert Whether the trigger operation is an insert
     * @param isUpdate Whether the trigger operation is an update
     **/
    public static void processCases(Map<Id, Case> newMap, Map<Id, Case> oldMap, Boolean isInsert, Boolean isUpdate) {
        if (bypassExternalActions || newMap == null || newMap.isEmpty()) {
            return;
        }

        Set<Id> caseIdsToSend = new Set<Id>();
        for (Case cNew : newMap.values()) {
            if (cNew == null) continue;
            if (cNew.GrandAccount__c != PELAYO_ACCOUNT_CODE) continue;

            if (isInsert) {
                caseIdsToSend.add(cNew.Id);
                continue;
            }

            Case cOld = oldMap != null ? oldMap.get(cNew.Id) : null;
            if (cOld == null) {
                caseIdsToSend.add(cNew.Id);
                continue;
            }

            if (isRelevantCaseChange(cOld, cNew)) {
                caseIdsToSend.add(cNew.Id);
            }
        }

        if (!caseIdsToSend.isEmpty()) {
            if (!System.isFuture() && !System.isQueueable() && !System.isBatch()) {
                PelayoUpdateClaimService.enqueue(caseIdsToSend);
            }
        }
    }

    /**
     * @description Enqueues Pelayo updateClaim callouts for a given set of Case Ids, typically invoked from related-object triggers (e.g. InsurableCoverage__c).
     * @param caseIds Set of Case Ids to process
     **/
    public static void processCaseIds(Set<Id> caseIds) {
        if (bypassExternalActions || caseIds == null || caseIds.isEmpty() || !shouldRunRelatedObjectCallouts()) {
            return;
        }
        if (System.isFuture() || System.isQueueable() || System.isBatch()) {
            return;
        }
        PelayoUpdateClaimService.enqueue(caseIds);
    }

    private static Boolean shouldRunRelatedObjectCallouts() {
        return !isIntegrationUser();
    }

    private static Boolean isIntegrationUser() {
        if (treatCurrentUserAsIntegrationUser != null) {
            return treatCurrentUserAsIntegrationUser;
        }

        if (cachedIsIntegrationUser != null) {
            return cachedIsIntegrationUser;
        }

        String currentUserName;
        try {
            currentUserName = [SELECT Name FROM User WHERE Id = :UserInfo.getUserId()].Name;
        } catch (Exception e) {
            currentUserName = null;
        }

        cachedIsIntegrationUser = (currentUserName == PELAYO_INTEGRATION_USER_NAME);
        return cachedIsIntegrationUser;
    }

    /**
     * @description Determines whether a Case update contains changes to fields that are relevant to the Pelayo updateClaim integration.
     * @param oldC Previous version of the Case record
     * @param newC Updated version of the Case record
     * @return Boolean True if at least one monitored field has changed
     **/
    @TestVisible
    static Boolean isRelevantCaseChange(Case oldC, Case newC) {
        return oldC.Subject != newC.Subject ||
            oldC.InsurerClaimReference__c != newC.InsurerClaimReference__c ||
            oldC.ExponentialQuadrant__c != newC.ExponentialQuadrant__c ||
            oldC.ClaimantDescription__c != newC.ClaimantDescription__c ||
            oldC.ClaimantName__c != newC.ClaimantName__c ||
            oldC.QuestionnaireComments__c != newC.QuestionnaireComments__c ||
            oldC.IncidentDate__c != newC.IncidentDate__c ||
            oldC.ClaimDate__c != newC.ClaimDate__c ||
            oldC.Reason__c != newC.Reason__c ||
            oldC.SubReason__c != newC.SubReason__c ||
            oldC.ClaimTypeIdentifier__c != newC.ClaimTypeIdentifier__c ||
            oldC.SituationType__c != newC.SituationType__c ||
            oldC.Urgent__c != newC.Urgent__c ||
            oldC.VitalOrganAffected__c != newC.VitalOrganAffected__c ||
            oldC.AssistanceService__c != newC.AssistanceService__c ||
            oldC.CurrentProvisionAmount__c != newC.CurrentProvisionAmount__c ||
            oldC.Deductible__c != newC.Deductible__c ||
            oldC.DeductibleUsed__c != newC.DeductibleUsed__c ||
            oldC.DamagesIncurred__c != newC.DamagesIncurred__c ||
            oldC.Marcadores__c != newC.Marcadores__c ||
            oldC.WantsSMSNotifications__c != newC.WantsSMSNotifications__c ||
            oldC.WantsEmailNotifications__c != newC.WantsEmailNotifications__c ||
            oldC.WantsWhatsAppNotifications__c != newC.WantsWhatsAppNotifications__c ||
            oldC.ClaimsHandlerName__c != newC.ClaimsHandlerName__c ||
            oldC.ClaimsHandlerEmail__c != newC.ClaimsHandlerEmail__c ||
            oldC.ContactId != newC.ContactId;
    }
}